'use client';

import { useEffect, useState } from 'react';
import { classifyDocument, DocumentType } from '@/lib/document-ai';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';

const TEST_FILES = [
    {
        name: 'bank_chase.txt',
        type: 'BANK_STATEMENT',
        content: `CHASE TOTAL CHECKING
JPMorgan Chase Bank, N.A.
P.O. Box 659754
San Antonio, TX 78265-9754

Statement Period: October 12, 2024 through November 10, 2024
Account Number: 000000123456789

CHECKING SUMMARY
Beginning Balance      $5,432.10
Deposits and Additions $3,200.00
ATM & Debit Card Withdrawals - $1,500.00
Electronic Withdrawals - $800.00
Ending Balance         $6,332.10

TRANSACTION DETAIL
DATE        DESCRIPTION                     AMOUNT
10/15       Deposit - Payroll              3,200.00
10/18       Debit Card Purchase - Target     -54.32
10/20       ATM Withdrawal                  -100.00
11/01       Payment to Chase Credit Card    -500.00`
    },
    {
        name: 'paystub_adp.txt',
        type: 'PAY_STUB',
        content: `ADP EARNINGS STATEMENT
Company: Tech Solutions Inc.
Employee: John Doe
Employee ID: 98765
Pay Period: 10/01/2024 - 10/15/2024
Pay Date: 10/20/2024

EARNINGS
Rate      Hours     This Period     YTD Amount
Regular       50.00     80.00     4,000.00        80,000.00
Bonus                             1,000.00        5,000.00
Gross Pay                         5,000.00        85,000.00

TAXES
Fed Income Tax                    800.00          16,000.00
Social Security                   310.00          5,270.00
Medicare                          72.50           1,232.50
State Income Tax                  200.00          4,000.00

DEDUCTIONS
401(k)                            250.00          5,000.00
Health Ins                        150.00          3,000.00

NET PAY                           $3,217.50

Direct Deposit Distribution:
Bank of America ...1234           $3,217.50`
    },
    {
        name: 'tax_1040.txt',
        type: 'TAX_RETURN',
        content: `Form 1040        Department of the Treasury - Internal Revenue Service
U.S. Individual Income Tax Return        2023
OMB No. 1545-0074

Filing Status: Single
Your First Name: John    Last Name: Doe
Your Social Security Number: 123-45-6789

Income
1a. Total amount from Form(s) W-2, box 1:    $85,000.00
2b. Taxable interest:                        $150.00
3b. Ordinary dividends:                      $500.00
...
9. Total Income:                             $85,650.00

Adjusted Gross Income
11. Adjusted Gross Income:                   $85,650.00

Standard Deduction or Itemized Deductions
12. Standard Deduction:                      $13,850.00

Tax and Credits
16. Tax:                                     $14,500.00
24. Total Tax:                               $14,500.00

Payments
25a. Federal income tax withheld:            $16,000.00

Refund
34. Amount you overpaid:                     $1,500.00`
    },
    {
        name: 'bank_credit_union.txt',
        type: 'BANK_STATEMENT',
        content: `MEMBER ACCOUNT STATEMENT
Local Community Credit Union
123 Main St, Hometown, USA

Member Name: Jane Smith
Member Number: 123456
Statement Date: 11/30/2024

SHARE SAVINGS - ID 00
Previous Balance: $10,000.00
Dividends Earned: $15.50
Deposits: $500.00
Withdrawals: $0.00
New Balance: $10,515.50

CHECKING - ID 10
Previous Balance: $2,500.00
Deposits: $4,000.00
Withdrawals: $3,800.00
New Balance: $2,700.00

Activity:
11/05   Payroll Deposit          $2,000.00
11/15   Mortgage Payment        -$1,800.00
11/20   Payroll Deposit          $2,000.00
11/25   Auto Loan Payment       -$400.00

YTD Dividends: $145.67
YTD Interest Paid: $0.00`
    },
    {
        name: 'paystub_quickbooks.txt',
        type: 'PAY_STUB',
        content: `Pay Stub
Generated by QuickBooks
Employer: Small Biz LLC
100 Enterprise Way

Employee: Michael Scott
Pay Date: 11/15/2024
Pay Period: 11/01/2024 to 11/14/2024

Pay
Description        Rate    Hours    Current    YTD
Salary                     40.00    2,500.00   55,000.00

Taxes
Federal Withholding                 300.00     6,600.00
Social Security                     155.00     3,410.00
Medicare                            36.25      797.50
State Withholding                   100.00     2,200.00

Deductions
Medical                             50.00      1,100.00

Summary
Gross Pay: 2,500.00
Total Taxes: 591.25
Total Deductions: 50.00
Net Pay: 1,858.75

Check Number: 1054`
    },
    {
        name: 'business_license.txt',
        type: 'BUSINESS_LICENSE',
        content: `BUSINESS LICENSE
State of New York
License Number: BL-123456789

Business Name: Smith Consulting LLC
Owner: John Smith
Address: 123 Business Rd, New York, NY 10001
Type: Limited Liability Company (LLC)

Issue Date: 01/15/2020
Expiration Date: 01/15/2025
Status: ACTIVE

This certifies that the above named business is authorized to conduct business within the state.

Secretary of State
Signature: [Seal]`
    },
    {
        name: 'loan_application_1003.txt',
        type: 'FORM_1003',
        content: `Uniform Residential Loan Application
Freddie Mac Form 65   Fannie Mae Form 1003

Section 1: Borrower Information. This section asks about your personal information and your income from employment and other sources.

1a. Personal Information
Name (First, Middle, Last, Suffix): John Quincy Borrower
Social Security Number: 123-45-6789
Date of Birth (mm/dd/yyyy): 01/15/1980
Citizenship: [x] U.S. Citizen
Marital Status: Married
Dependents: 2
Contact Information
Home Phone: (555) 123-4567    Cell Phone: (555) 987-6543    Work Phone:
Email: john.borrower@example.com
Current Address: Street: 123 Maple Street   Unit #:
City: Springfield   State: IL   Zip: 62704   Country: USA
How long at current address? 5 Years

1b. Current Employment/Self-Employment and Income
Employer or Business Name: Acme Corp
Phone: 555-555-5555
Street: 456 Business Rd   City: Springfield   State: IL   Zip: 62704
Position: Manager   Start Date: 01/01/2015
Gross Monthly Income
Base: $ 5,000.00
Overtime: $ 0.00
Bonus: $ 1,000.00
Commissions: $ 0.00
Other: $ 0.00
Total: $ 6,000.00

Section 2: Financial Information - Assets and Liabilities.
2a. Assets - Bank Accounts, Retirement, and Other Accounts You Have
Account Type: Checking   Financial Institution: Chase Bank   Account Number: 1234   Cash or Market Value: $ 10,000.00
Account Type: Savings    Financial Institution: Chase Bank   Account Number: 5678   Cash or Market Value: $ 25,000.00

2b. Other Assets You Have
...

2c. Liabilities - Credit Cards, Other Debts, and Leases that You Owe
Account Type: Credit Card   Company Name: Visa   Account Number: 1111   Unpaid Balance: $ 500.00   Monthly Payment: $ 50.00
Account Type: Auto Loan     Company Name: Ford Credit   Account Number: 2222   Unpaid Balance: $ 15,000.00   Monthly Payment: $ 350.00

Section 3: Financial Information - Real Estate.
...

Section 4: Loan and Property Information.
4a. Loan and Property Information
Loan Amount: $ 300,000.00
Loan Purpose: Purchase
Property Address: Street: 789 Oak Avenue   Unit #:
City: Springfield   State: IL   Zip: 62704   Country: USA
Occupancy: Primary Residence

Section 5: Declarations.
...

Section 9: Loan Originator Information.
Loan Originator Name: Jane Broker
Loan Originator Identifier: 98765
Loan Originator Company Name: Best Mortgage Co
Loan Originator Company Identifier: 54321`
    }
];

interface TestResult {
    name: string;
    expected: string;
    detected: string;
    confidence: number;
    pass: boolean;
    reason?: string;
}

export default function ClassifierTestPage() {
    const [results, setResults] = useState<TestResult[]>([]);
    const [isRunning, setIsRunning] = useState(false);

    const runTests = async () => {
        setIsRunning(true);
        const newResults: TestResult[] = [];

        for (const testFile of TEST_FILES) {
            // Create a File object
            const file = new File([testFile.content], testFile.name, { type: 'text/plain' });

            try {
                const result = await classifyDocument(file);
                newResults.push({
                    name: testFile.name,
                    expected: testFile.type,
                    detected: result.type,
                    confidence: result.confidence,
                    pass: result.type === testFile.type,
                    reason: result.failureReason
                });
            } catch (error) {
                newResults.push({
                    name: testFile.name,
                    expected: testFile.type,
                    detected: 'ERROR',
                    confidence: 0,
                    pass: false,
                    reason: String(error)
                });
            }
        }

        setResults(newResults);
        setIsRunning(false);
    };

    useEffect(() => {
        runTests();
    }, []);

    return (
        <div className="min-h-screen bg-background p-8 text-slate-900 dark:text-white">
            <div className="max-w-4xl mx-auto">
                <h1 className="text-3xl font-bold mb-8 text-slate-900 dark:text-white">Document Classifier Verification</h1>
                <Card className="bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700">
                    <CardHeader>
                        <CardTitle>Test Results</CardTitle>
                    </CardHeader>
                    <CardContent>
                        {isRunning ? (
                            <div className="text-center py-8">Running classification tests...</div>
                        ) : (
                            <div className="overflow-x-auto">
                                <table className="w-full text-left border-collapse">
                                    <thead>
                                        <tr className="border-b border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-400">
                                            <th className="p-4">File Name</th>
                                            <th className="p-4">Expected</th>
                                            <th className="p-4">Detected</th>
                                            <th className="p-4">Confidence</th>
                                            <th className="p-4">Status</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {results.map((result, idx) => (
                                            <tr key={idx} className="border-b border-slate-200 dark:border-slate-700/50">
                                                <td className="p-4 font-mono text-sm text-slate-900 dark:text-slate-300">{result.name}</td>
                                                <td className="p-4 text-blue-600 dark:text-blue-400">{result.expected}</td>
                                                <td className={`p-4 font-bold ${result.pass ? 'text-green-600 dark:text-green-400' : 'text-red-600 dark:text-red-400'}`}>
                                                    {result.detected}
                                                </td>
                                                <td className="p-4 text-slate-900 dark:text-white">{(result.confidence * 100).toFixed(1)}%</td>
                                                <td className="p-4">
                                                    {result.pass ? (
                                                        <span className="px-2 py-1 rounded bg-green-100 dark:bg-green-500/20 text-green-700 dark:text-green-400 text-xs font-bold">PASS</span>
                                                    ) : (
                                                        <span className="px-2 py-1 rounded bg-red-100 dark:bg-red-500/20 text-red-700 dark:text-red-400 text-xs font-bold">FAIL</span>
                                                    )}
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        )}
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}
